### ISSUE TITLE
Decode device parameters

### ISSUE THREAD

**Issue by cdytoby** [mobfishgmbh/Cardboard-VR-Unity-SDK#1]
## Description

Device Parameters are encoded using Protocol Buffer, we need to find a way to decode it, so that user can understand which Cardboard he's in.

## Technical Detail

https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/cardboard_v1/cardboard_v1.cc    
According to this file, vendor and model strings are in parameters.

## Tasks

- [x] Decode Device Parameters, and print vendor and model in log.
- [x] Get all the possible values from Device Parameters.

**Comment by rohantipare** [comment]
The Device Parameters is saved as a string in User Defaults for key : "com.google.cardboard.sdk.DeviceParamsAndTime"

Here is the actual code in file https://github.com/googlevr/cardboard/blob/master/sdk/qrcode/ios/device_params_helper.mm

line 28: NSUserDafaults key
line 158: writes the device parameter to NSUserDefault every time it updates.

sample log:
"VR BOX (Measured by 'Sites in VR')\^R\^FVR BOX\^]Lÿà=%%\^FÅ=*\^P√\^]pB√\^]pB√\^]pB√\^]pBX

**Comment by rohantipare** [comment]
Implementation done. Pushed on branch 'deviceParameters'.

**Comment by cai-mobfish** [comment]
@rohantipare Thank you for the work.

I have a few questions:

- I noticed that you implemented the whole Protocol Buffer's C# source into this project, is it possible to not implement the whole source code? like a single netstandard compatible dll file.
- I noticed that `Assets/Cardboard/Scripts/CardboardDevice.cs` is automatically generated. And it's "Generated by the protocol buffer compiler", source is `cardboard_device.proto`, why is this file not included in the project?

**Comment by rohantipare** [comment]
1: I will work on DLL solution.
2: I will add the file .proto file in the project.

**Comment by cai-mobfish** [comment]
@rohantipare I just did some research, I think I know too little about this protocol buffer thing. I don't think .proto file is necessary in this project, a compiled file should be enough.

But I also want to prevent unnecessary code, so after view some more files, I just noticed one thing: there is already a compiled `DeviceParam` in `libsdk.a`.

The source codes are here: https://github.com/googlevr/cardboard/blob/master/proto/cardboard_device.proto  
https://github.com/googlevr/cardboard/tree/master/proto

and there are some cardboard device related files in libsdk.a, I noticed it by simply decompressing it. So is there anyway to expose these apis in unity?

**Comment by rohantipare** [comment]
Yes. My intention was to do the same. But if you check out the HelloCardboard project in Google repository, 'DeviceParam' is not accessible unless you modify dependencies and/or header search paths.
Also I think the protocol buffer aims to achieve language agnostic sharing of data.
These are my findings and opinion. Let me know if I missed something.

**Comment by cai-mobfish** [comment]
I'm not familiar with c++ things, but I understand what you mean. 

I think a dll solution should be better.

Also, on second thought, I think .proto file should be included in project, along with the compiled .cs file. Can you change the namespace to "MobfishCardboard" so that this new file's namespace to match the rest?

After you're done, assign this issue to me, I need to add a license notice of the protocol buffer.

**Comment by rohantipare** [comment]
Sure. I will do that.

**Comment by rohantipare** [comment]
@cai-mobfish Below are the modifications:
1: Use DLL for google protocol buffer.
2: Change namespace to 'MobfishCardboard'
3: Add carboard_device.proto at 'Resources\ProtocolBuffer'
Latest changes are pushed to branch 'deviceParameters'

**Comment by cai-mobfish** [comment]
@rohantipare   
One more question:

Do you have any specific reason why this proto file in Resources? Will this file being loaded during runtime? Can I move to other location?

**Comment by rohantipare** [comment]
Yes. You can. The .proto file has no usage.
