### ISSUE TITLE
REQUEST: use Unity ARFoundation for Tracked Pose Driver

### ISSUE THREAD

**Issue by hawkwood** [mobfishgmbh/Cardboard-VR-Unity-SDK#11]
A benefit to just jumping straight in and letting Unity's existing ARFoundation handle the rotational tracking, is that we could also easily turn on positional tracking for devices that support it, and now have 6DOF headsets.

**Comment by cai-mobfish** [comment]
It is not our focus but I'll see what I can do after 1.0 Release. I'll keep this ticket.

**Comment by hawkwood** [comment]
That's understandable, then my alternate request is to decouple the head tracking part from the main VR script.  Please take a look at my commit on my fork of this project: https://github.com/hawkwood/Cardboard-VR-Unity-SDK/commit/b27f56245d97ef3b48c995f1113e54f468563981
If you do that, then I can easily disable it, and enable ARFoundation tracking manually without having to continuously modify the scripts as the project progresses.

**Comment by cai-mobfish** [comment]
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/issues/19

I created a new ticket for it, thanks for the feedback.

**Comment by cai-mobfish** [comment]
@hawkwood 

Hello, I just updated `public_dev` branch, and now the main camera components are decoupled. You can setup your own camera prefab with it.
