### ISSUE TITLE
Error when archive xcode project, it seems arm7 and arm64 linking is wrong

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#12]
## Details

Error message:

ld: warning: ignoring file /Volumes/MyData/Workspaces/XCodeWorkspace/mobfishCardboard_XCode/Libraries/Cardboard/Plugins/iOS/libsdk.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64

## Technical Details

It seems libsdk.a is arm64 only, it should be available for both arm7 and arm 64

**Comment by rohantipare** [comment]
@cai-mobfish 
The Universal library is built and pushed to branch 'UniversalLib' branch. I was able to create the archive successfully.

**Comment by cai-mobfish** [comment]
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/issues/18

This issue is handled in another issue, because cardboard sdk is modified and recompiled.
