### ISSUE TITLE
After scan the qr code through camera, unity doesn't get any callback or feedback.

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#18]
## Technical Details

OnApplicationFocus and OnApplicationPause doesn't trigger when scan the qr code from camera.  
We need to find a way to get a callback without using update or long time coroutine.

**Comment by rohantipare** [comment]
@cai-mobfish 
The implementation is complete. Changes are merged with 'public_dev' and pushed to branch 'QRCallback'. 
Some important points:
1: The sdk 'lbsdk.a' is modified to make provision for the callback.
2: Add new library 'libCardboardUtility.a' to handle native implementation.
3: New plugin functions added in 'CardboardQrCode.cs':
     a: registerObserver
     b: deregisterObserver

Files attached:
1: File modified in SDK: arcade/ios/qr_code.mm - line 42
[qr_code.mm.zip](https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/files/4528578/qr_code.mm.zip)
2: Source files of 'libCardboardUtility.a':
[libCardboardUtility.zip](https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/files/4528574/libCardboardUtility.zip)

**Comment by rohantipare** [comment]
I have also built and imported Universal Lib of 'libCardboardUtility.a'. Latest changes are pushed to branch "QRCallback"
