### ISSUE TITLE
Add Recenter functionality

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#27]
## Detail

This is a standard Recenter function, it can be used to make camera face "Front" in scene.

**Comment by rohantipare** [comment]
@cai-mobfish 
I have implemented the Recenter functionality and pushed on branch 'recenterCamera'
Function: RecenterCamera() in CardboardHeadTracker.cs
Scene: 'demoScene - test recenter'
The demo script recenters the camera every 5 seconds.

**Comment by cai-mobfish** [comment]
@rohantipare 
Thanks for the implementation, this recenter works, but we also need another kind of recenter, that the camera only "recenter horizontally", can you do an extra method for this?

Also, I did a little change in this branch, the DemoScene also contains a button to recenter now. You  can pull this branch before making another changes.

**Comment by rohantipare** [comment]
Sure, I will implement the recenter horizontal only functionality

**Comment by rohantipare** [comment]
@cai-mobfish I have implemented the Horizontal only recenter. Changes are pushed to branch 'recenterCamera'

**Comment by cai-mobfish** [comment]
Tested, works.
Did an extra commit to remove unused files.

Merged into public-dev.
