### ISSUE TITLE
Update native Cardboard library to version 1.1.0

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#42]
## Detail

- iOS .a file should be updated.
- Several methods are added or removed.
- Changes made in qr code callback should also be included.

Added:  
```
int CardboardQrCode_getQrCodeScanCount();

void CardboardQrCode_getCardboardV1DeviceParams(uint8_t** encoded_device_params, int* size);

void CardboardLensDistortion_getFieldOfView(CardboardLensDistortion* lens_distortion, CardboardEye eye, float* field_of_view);

void CardboardLensDistortion_getEyeFromHeadMatrix(
    CardboardLensDistortion* lens_distortion, CardboardEye eye,
    float* eye_from_head_matrix);

void CardboardLensDistortion_getProjectionMatrix(
    CardboardLensDistortion* lens_distortion, CardboardEye eye, float z_near,
    float z_far, float* projection_matrix);
```

Removed:  

```
CardboardLensDistortion_getEyeMatrices
```

**Comment by rohantipare** [comment]
@cai-mobfish The SDK is updated to v1.1.0. Changes are pushed on branch 'updateSDK'.

**Comment by cai-mobfish** [comment]
@rohantipare    
Can you rebuild this .a file with both armv7 and arm64 support? It has issue about "undefined symbol" when I try to archive this project.

**Comment by cai-mobfish** [comment]
I added the method `CardboardQrCode_getQrCodeScanCount()`, which could be useful to identify if user has already scanned a cardboard.

**Comment by rohantipare** [comment]
@cai-mobfish I will look into the archiving issue and see if the function CardboardQrCode_getQrCodeScanCount() can be used to detect qr code scan.

**Comment by cdytoby** [comment]
@rohantipare   
Just check the archiving issue, it's the same issue as https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/issues/12 this one.

CardboardQrCode_getQrCodeScanCount() is now logged after qr code scan now, so it's not necessary to do more here. I'll make another ticket with "set default qr code", which would be the exact same behaviour as the old cardboard.

**Comment by rohantipare** [comment]
@cai-mobfish The archiving issue is fixed. Changes are pushed to branck 'updateSDK'.

**Comment by cai-mobfish** [comment]
Tested and merged into public-dev.
