### ISSUE TITLE
Conditional stops editor from working

### ISSUE THREAD

**Issue by hawkwood** [mobfishgmbh/Cardboard-VR-Unity-SDK#59]
This line:

https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/blob/2b1afbde9f192e34929414435f805c1d81d4905e/Assets/Cardboard/Scripts/CardboardManager.cs#L140

should be:

            if (par.Item2 > 0 || Application.isEditor)

**Comment by cai-mobfish** [comment]
Thanks, I just released a new version with this fix.
