### ISSUE TITLE
Get correct device orientation from Cardboard SDK

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#6]
## Technical Detail

Currently, `Input.gyro` is used to retrieve and calculate device orientation, because there are problems with cardboard way to get the orientation. The quaternion needs converted, but the bigger issue is, the "rotation speed" is almost 2 times faster, rotate device 90 degrees makes in-game camera 180 degrees rotation. Somethings are definately wrong with the usage.  

Related file is `CardboardHeadTracker.cs`

**Comment by rohantipare** [comment]
I think the float array for orientation from native to Unity is not transferred the right way. I found this by:
1: Inserting the a log in the function call 'Cardboard_getPose' to print orientation values in the sdk
2: Building the sdk with log, and importing it in unity
3: Observing the orientation values at the unity side, on the device screen.

The orientation values from the native side (printed on log in xcode) does not match with values on unity side.
It has something to do with managed(Unity/c#) and unmanaged memory(c++) conversion. I have tried using GCHandle, Marshall. Not been able to solved so far.

**Comment by rohantipare** [comment]
@cai-mobfish 
The issue is fixed. Changes are pushed to branch 'deviceOrientation'.

**Comment by cai-mobfish** [comment]
CACurrentMediaTime is iOS native method. Some other equivalent method in c# or unity is needed here.

On Android, the equivalent is written in util, with some extra calculation.

https://github.com/googlevr/cardboard/blob/master/hellocardboard-android/src/main/jni/util.cc
```
long GetMonotonicTimeNano() {
  struct timespec res;
  clock_gettime(CLOCK_MONOTONIC, &res);
  return (res.tv_sec * kNanosInSeconds) + res.tv_nsec;
}
```

**Comment by cai-mobfish** [comment]
iOS code:

```
  double targetTime = CACurrentMediaTime() * 1e9;
  targetTime += kPredictionTimeWithoutVsyncNanos;
```

Android code:

```
  long monotonic_time_nano = GetMonotonicTimeNano();
  monotonic_time_nano += kPredictionTimeWithoutVsyncNanos;
```

The goal is to have a monotonic time in nanoseconds.

**Comment by cai-mobfish** [comment]
Do a refactor, push the branch.

**Comment by cai-mobfish** [comment]
Done.
