### ISSUE TITLE
Android: Camera movement is not fluent.

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#61]
## Description:

The camera moves like it's "laggy". It could be due to 2 reasons:
- Performance on my smartphone is bad, or something here is bad optimized (low framerate)
- The camera movement implementation is wrong due to "monotonic time"

**Comment by hawkwood** [comment]
Has Unity's own gyro implementation been tried on device, as a replacement for using the native libraries?
https://docs.unity3d.com/ScriptReference/Gyroscope.html

**Comment by cdytoby** [comment]
Turns out it's just pure framerate issue. targetFramerate should set to 60 on Android too.

Information in my head was old.
