### ISSUE TITLE
Import "mobfishCardboard-1.0-Release-2020-0808.unitypackage" error

### ISSUE THREAD

**Issue by imkrystal** [mobfishgmbh/Cardboard-VR-Unity-SDK#81]
Hi mobifish!

Thank you for your amazing package. When I run in iOS 14, it worked!!!
But when I create a new project => import "mobfishCardboard-1.0-Release-2020-0808.unitypackage", it's seem that error (see image i have attach).

<img width="643" alt="Screen Shot 2020-11-04 at 15 57 25" src="https://user-images.githubusercontent.com/46667579/98090325-745c0180-1eb6-11eb-8dba-8f35ed9018b1.png">

How can I resolved this problem. I'm using Unity 2018.4.28f1.

Thank you so much!

Best Regards!

**Comment by cdytoby** [comment]
Thiss error message indicates that there are multiple "Protocol Buffer" dlls imported in this project. You should delete one of them. Either the dll from this plugin, or other plugins.

**Comment by imkrystal** [comment]
Hi @cdytoby 
Thank you for your answer.
I check and see that I have 2 "Protobuf". 

In your plugin:
<img width="314" alt="Screen Shot 2020-11-05 at 10 20 39" src="https://user-images.githubusercontent.com/46667579/98193791-92764000-1f50-11eb-8a78-9ca977af09fd.png">

Another in GoogleARCore:
<img width="295" alt="Screen Shot 2020-11-05 at 10 21 17" src="https://user-images.githubusercontent.com/46667579/98193859-af127800-1f50-11eb-8e9f-05a088a33633.png">

You think that I should delete in your plugin or in GoogleARCore. It's safe and cardboard work normal when I delete "Protobuf" in your plugin?

Thank you so much.
Best Regards!

**Comment by cdytoby** [comment]
Yes, make a backup and try it.

**Comment by imkrystal** [comment]
Delete "Protobuf" in your project it make error in Script so I deleted and backup "Protobuf" in GoogleARCore. I hope that nothing happen with me but I have a question: 
- Can I use your Cardboard and ARKit, ARCore together? (Because I see that: OpenGL ES 3.0 and Metal(iOS) and Vulkan(Android) Support (as well as OpenGL ES 2.0)). 
- It will work with Android devices?

**Comment by cdytoby** [comment]
I've never used ARKit or ARCore before so I don't really know. All I know is this plugin works for both iOS and Android. And there are some users already successfully implemented it with AR so I believe it's suppose to work with other plugins. 

You can just try it yourself, this plugin don't gave people limitation, and all the source codes are here.

BTW, it's weird that delete Protobuf in this project will result errors when the other Protobuf exists.

**Comment by imkrystal** [comment]
Thank you for your answer. I will try this.
"This is an unofficial Google Cardboard Unity SDK, implemented from new Google Cardboard open source project."
=> new Google Cardboard, you mean that is Google Cardboard XR Plugin right?

**Comment by cdytoby** [comment]
Yes, and no.

The new Google Cardboard SDK includes a Base SDK in C++, with a native Android and native iOS plugin. Unity Plugin is based on these native plugins, which also includes Subsystem for XR Plugin Management from Unity.

This repository uses the native Android and iOS plugin part, and doesn't use XR Plugin Management from Unity. Instead, it uses an old solution, which the first version of Cardboard for Unity did.

**Comment by imkrystal** [comment]
Thank you for your answer.

I hope that you plugin will have more functions, more optimizations, ... for a next release.
Again. Thank you so much for amazing plugin.
Maybe I will close this topic, if I have something need to know, I will open this topic again.

Best Regards!
