### ISSUE TITLE
Importing gives an error

### ISSUE THREAD

**Issue by MSachs1** [mobfishgmbh/Cardboard-VR-Unity-SDK#87]
I get these two error messages when trying to import the package through the package manager in Unity.

"Cannot perform upm operation: Unable to add package [https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK.git]: [https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository."

"Error adding package: https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK.git."

What am I doing wrong? Other packages I tried work as intended using the respective link

**Comment by imkrystal** [comment]
You can download "file.unitypackage" (link below) and import this package in Unity Project. 
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/releases

**Comment by MSachs1** [comment]
> You can download "file.unitypackage" (link below) and import this package in Unity Project.
> https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/releases

Thanks a lot!

**Comment by cdytoby** [comment]
This package can't be used by unity package manager, you have to import it manually.
